# Generated by Django 4.2.24 on 2025-09-19 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceRecord',
            new_name='Attendance',
        ),
        migrations.RenameModel(
            old_name='ScanSession',
            new_name='Session',
        ),
    ]
