# Generated by Django 4.2.24 on 2025-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_attendancerecord_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='numeric_code',
            field=models.CharField(max_length=2),
        ),
    ]

# Generated by Django 4.2.24 on 2025-09-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_attendancerecord_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='numeric_code',
            field=models.CharField(max_length=2),
        ),
    ]
