# Generated by Django 4.2.24 on 2025-09-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_session_numeric_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='signin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='signout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
